USE [master]
GO

/****** Object:  Database [YourPEL]    Script Date: 02/05/2018 20:00:22 ******/
CREATE DATABASE [YourPEL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YourPEL', FILENAME = N'D:\Programas\MicrosoftSQLServer\MSSQL14.SQLEXPRESS\MSSQL\DATA\YourPEL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'YourPEL_log', FILENAME = N'D:\Programas\MicrosoftSQLServer\MSSQL14.SQLEXPRESS\MSSQL\DATA\YourPEL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [YourPEL] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YourPEL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YourPEL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YourPEL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YourPEL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YourPEL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YourPEL] SET ARITHABORT OFF 
GO

ALTER DATABASE [YourPEL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YourPEL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YourPEL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YourPEL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YourPEL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YourPEL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YourPEL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YourPEL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YourPEL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YourPEL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YourPEL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YourPEL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YourPEL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YourPEL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YourPEL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YourPEL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YourPEL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YourPEL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [YourPEL] SET  MULTI_USER 
GO

ALTER DATABASE [YourPEL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YourPEL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [YourPEL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [YourPEL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [YourPEL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [YourPEL] SET QUERY_STORE = OFF
GO

USE [YourPEL]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [YourPEL] SET  READ_WRITE 
GO

