//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIGO
    {
        public int idArtigo { get; set; }
        public System.DateTime dataHora { get; set; }
        public string autor { get; set; }
        public string titulo { get; set; }
        public string texto { get; set; }
        public int ordemRelevancia { get; set; }
        public string tema { get; set; }
        public string subTema { get; set; }
        public string descricao { get; set; }
        public string urlYoutube { get; set; }
        public bool ativo { get; set; }
        public string url { get; set; }
    }
}
