//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIQUE
    {
        public string idClique { get; set; }
        public int idCookie { get; set; }
        public string dispositivo { get; set; }
        public string tipoClique { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
