//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public int idDocumento { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
        public string tema { get; set; }
    }
}
