//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.RESPOSTAs = new HashSet<RESPOSTA>();
        }
    
        public int ID_POST { get; set; }
        public string TITULO { get; set; }
        public string TEXTO { get; set; }
        public System.DateTime DATA_HORA { get; set; }
        public string TEMA { get; set; }
        public bool ATIVO { get; set; }
        public bool FECHADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPOSTA> RESPOSTAs { get; set; }
    }
}
