//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACAO
    {
        public int idPUBLICACAO { get; set; }
        public string titulo { get; set; }
        public string conteudo { get; set; }
    }
}
