//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPOSTA
    {
        public int ID_RESPOSTA { get; set; }
        public string TEXTO { get; set; }
        public System.DateTime DATA_HORA { get; set; }
        public int ID_UTILIZADOR { get; set; }
        public int ID_POST { get; set; }
    
        public virtual POST POST { get; set; }
        public virtual UTILIZADOR UTILIZADOR { get; set; }
    }
}
