//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourPEL.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILIZADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILIZADOR()
        {
            this.RESPOSTAs = new HashSet<RESPOSTA>();
        }
    
        public int ID_UTILIZADOR { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPOSTA> RESPOSTAs { get; set; }
    }
}
